commerce_payment.commerce_payment_gateway.plugin.helcim:
  type: commerce_payment_gateway_configuration
  mapping:
    redirect_method:
      type: string
      label: 'Redirect method'
    display_label:
      type: string
      label: 'The name of gateway'
    hosted_page_url:
      type: string
      label: 'URL of Hosted Page'
    secret_hash_key:
      type: string
      label: 'Secret hash key'
