<?php

/**
 * @file
 * Install, update and uninstall functions for the Student Calendar module.
 */

/**
 * Implements hook_install().
 */
function student_calendar_install() {
  \Drupal::messenger()->addMessage(t('Student Calendar module has been installed successfully.'));
}

/**
 * Implements hook_uninstall().
 */
function student_calendar_uninstall() {
  \Drupal::messenger()->addMessage(t('Student Calendar module has been uninstalled.'));
}
